const radarWatchlist = [
	"AALI", "ABBA", "ABMM", "ACES", "ACST", "ADCP", "ADHI", "ADMR", "ADRO", "AGII",
	"AGRO", "AKRA", "ALDO", "AMAG", "AMMN", "AMRT", "ANJT", "ANTM", "APLN", "ARCI",
	"ARNA", "ARTO", "ASBI", "ASDM", "ASGR", "ASII", "ASJT", "ASLC", "ASMI", "ASRM",
	"ASSA", "ASRI", "ATIC", "AUTO", "AVIA", "AWAN", "AXIO", "BABP", "BACA", "BAJA",
	"BALI", "BANK", "BAYU", "BBCA", "BNBR", "BBHI", "BBKP", "BBLD", "BBMD", "BBNI", "BBRI",
	"BBSI", "BBTN", "BBYB", "BDMN", "BELI", "BFIN", "BIRD", "BJBR", "BJTM", "BKSL",
	"BMRI", "BMTR", "BNBS", "BNGA", "BOBA", "BOLI", "BREN", "BRIS", "BRMS", "BRPT",
	"BSDE", "BSSR", "BTPN", "BUDI", "BUKA", "BUKK", "BULL", "BUMI", "BVIC", "BWPT",
	"BYAN", "CAMP", "CANI", "CARE", "CARS", "CASA", "CASS", "CATO", "CBRE", "CDIA",
	"CEKA", "CENT", "CFIN", "CGAS", "CHIP", "CINT", "CLEO", "CLPI", "CMNP", "CMRY",
	"COCO", "CPIN", "CSAP", "CSRA", "CTBN", "CTRA", "CTTH", "CUAN", "DART", "DEFI",
	"DEPO", "DEWA", "DFAM", "DGIK", "DGNS", "DIGI", "DILD", "DIMA", "DMAS", "DMND",
	"DNAR", "DNET", "DOID", "DPNS", "DPUM", "DRMA", "DSFI", "DSNG", "DSSA", "DUTI",
	"DVLA", "EAST", "ECII", "EDII", "ELTY", "ELSA", "EMDE", "EMTK", "ENRG", "EPMT", "ERAA",
	"ERAK", "ESIP", "ESSA", "ESTA", "EURO", "EXCL", "FAPA", "FAST", "FASW", "FILM",
	"FIRT", "FISH", "FITT", "FLMC", "FMII", "FORU", "FPNI", "GDST", "GDYR", "GEMA",
	"GEMS", "GGRM", "GJTL", "GOOD", "GREN", "GTBO", "GULA", "GWSA", "GZCO", "HAIS",
	"HDFA", "HDTX", "HEAL", "HERO", "HEXA", "HILL", "HITS", "HMSP", "HOKI", "HOTL",
	"HRTA", "HRUM", "HUMI", "IATA", "IBFN", "IBOS", "IBST", "ICBP", "ICON", "IDPR",
	"IFII", "IFSH", "IGAR", "IKAI", "IKBI", "IMAS", "IMJS", "IMPC", "INAF", "INAI",
	"INCF", "INCI", "INCO", "INDF", "INDO", "INDR", "INDS", "INDY", "INET", "INKP",
	"INOV", "INPC", "INPP", "INRU", "INTP", "IPCC", "IPCM", "IPOL", "IPTV", "IRRA",
	"ISAT", "ISSP", "ITMA", "ITMG", "JARR", "JAST", "JGLE", "JASU", "JECC", "JGPA", "JKON",
	"JKSW", "JMAS", "JPFA", "JRPT", "JSMR", "JSPT", "JTPE", "KAEF", "KARW", "KBAG",
	"KBLI", "KBLM", "KBLV", "KBRI", "KDSI", "KEEN", "KEJU", "KIAS", "KICI", "KIJA",
	"KINO", "KINR", "KKGI", "KLBF", "KMDS", "KMTR", "KOCI", "KOIN", "KONI", "KOPI",
	"KPIG", "KRAS", "KROX", "LEAD", "LPCK", "LPGI", "LPIN", "LPKR", "LPLI", "LPOP",
	"LPPF", "LSIP", "LSPT", "LTLS", "LUCK", "MAIN", "MAPA", "MAPB", "MAPI", "MARK",
	"MASA", "MAYA", "MBAP", "MBMA", "MBSS", "MBTO", "MCAS", "MCOR", "MCOL", "MDFC",
	"MDIA", "MDKA", "MDKI", "MEDC", "MEGA", "MERK", "META", "MFIN", "MFMI", "MGLV",
	"MGNA", "MICE", "MIDI", "MIKA", "MINA", "MIRE", "MITS", "MKPI", "MLBI", "MLIA",
	"MLND", "MLPT", "MMIX", "MNCN", "MNDO", "MPMX", "MPPA", "MRAT", "MREI", "MSIN",
	"MSKY", "MTDL", "MTEL", "MTLA", "MTRA", "MTSM", "MYOH", "MYOR", "MYTX", "NASA",
	"NASI", "NCKL", "NDKO", "NELI", "NELY", "NFCX", "NICE", "NICK", "NICL", "NIKL",
	"NINE", "NISP", "NOBU", "NRCA", "NSSS", "NTRD", "OASA", "OBMD", "OCAP", "OCMD",
	"OILS", "OKAS", "OMRE", "OPMS", "PALM", "PAMA", "PAMG", "PANI", "PANR", "PANS",
	"PBID", "PBRX", "PBSA", "PCAR", "PDES", "PEGE", "PEHA", "PGAS", "PGJO", "PIPA",
	"PJAA", "PKPK", "PLAS", "PLIN", "PLND", "PMMP", "PNBN", "PNBS", "PNIN", "PNLF",
	"PNSE", "POOL", "PORT", "POWR", "PPGL", "PPRE", "PRDA", "PRIM", "PSAB", "PSDN",
	"PSGO", "PSSI", "PTBA", "PTDU", "PTIS", "PTMP", "PTPP", "PTRO", "PTSN", "PTPW",
	"PUDP", "PWON", "PYFA", "PZZA", "RAJA", "RALS", "RATU", "RBMS", "RCCC", "RDTX",
	"RELI", "RICY", "RIGS", "RISE", "RMKE", "ROCK", "RODA", "ROTI", "SAFE", "SAME",
	"SAMF", "SAPX", "SBMA", "SCCO", "SCMA", "SCNP", "SDPC", "SDRA", "SEMA", "SFAN",
	"SFXI", "SGAR", "SGER", "SGLP", "SGRO", "SHID", "SIDO", "SILO", "SIMP", "SINK",
	"SIPD", "SKBM", "SKLT", "SKRN", "SMAR", "SMBR", "SLIS", "SMCB", "SMDM", "SMDR", "SMGR",
	"SMIL", "SMKL", "SMMA", "SMRA", "SMSM", "SNLK", "SOFA", "SONA", "SOSI", "SOTN",
	"SPMA", "SPTO", "SQMI", "SREI", "SRSN", "SRTG", "SSIA", "SSMS", "SSSI", "SSTM",
	"STAA", "STAR", "STTP", "SUPR", "SURE", "SWAT", "TALF", "TAPG", "TBIG", "TBLA",
	"TCID", "TCPI", "TDPM", "TEBE", "TECH", "TFCO", "TGRA", "TIFA", "TINC", "TINS",
	"TIPR", "TIRA", "TISC", "TKIM", "TLDN", "TLKM", "TMAN", "TMAS", "TMPO", "TNCA",
	"TOBA", "TOTE", "TOTO", "TOWR", "TPIA", "TPMA", "TRFA", "TRIM", "TRIN", "TRIO",
	"TRIS", "TRST", "TRUE", "TRUK", "TSPC", "TUGU", "TULT", "TYRE", "UANG", "UCID",
	"UECU", "UIDA", "ULTJ", "UNIC", "UNIT", "UNTR", "UNVR", "URBN", "USBP", "VKTR",
	"VRNA", "VTNY", "WEGE", "WEHA", "WICO", "WIDI", "WIFI", "WIIM", "WIKA", "WIMP",
	"WINE", "WINS", "WITC", "WMUU", "WOOD", "WSBP", "WTON", "YPAS", "YULE", "ZBRA",
	"ZONE", "ZYRX"
];

const uniqueRadarWatchlist = [...new Set(radarWatchlist)];