// ==================== DATABASE RADAR WATCHLIST ====================
const radarWatchlist = [
	"AALI", "ABDA", "ABMM", "ACES", "ACST", "ADCP", "ADHI", "ADMF", "ADMR", "ADRO", 
	"AGAR", "AGII", "AGRO", "AGRS", "AHAP", "AIMS", "AISA", "AKRA", "AKSI", "ALDO", 
	"AMAR", "AMFG", "AMIN", "AMMN", "AMOR", "AMRT", "ANDI", "ANJT", "ANTM", "APEX", 
	"APIC", "APLN", "ARCI", "ARNA", "ARTA", "ARTO", "ASGR", "ASII", "ASJT", "ASRI", 
	"ASSA", "AUTO", "AVIA", "BABP", "BACA", "BAJA", "BALI", "BANK", "BAPIN", "BATA", 
	"BBCA", "BBHI", "BBKP", "BBLD", "BBMD", "BBNI", "BBRI", "BBRM", "BBTN", "BBYB", 
	"BCIC", "BCIP", "BDMN", "BEBS", "BEEF", "BEST", "BFIN", "BGOK", "BGTG", "BHAT", 
	"BHIT", "BIKA", "BIMA", "BINA", "BIPI", "BIRD", "BISI", "BJBR", "BJTM", "BKDP", 
	"BKSL", "BLAZ", "BLTZ", "BMAS", "BMHS", "BMRI", "BMTR", "BNBR", "BNGA", "BNII", 
	"BNLI", "BOGA", "BPII", "BRIS", "BRMS", "PTBA", "BRPT", "BSDE", "BSIM", "BSSR", 
	"BSWD", "BTEK", "BTPS", "BUKA", "BUKK", "BULL", "BVIC", "BWPT", "BYAN", "CASS", 
	"CASA", "CCEI", "CENT", "CFIN", "CINT", "CITA", "CITY", "CLPI", "CMNP", "CMNT", 
	"CNKO", "CNTX", "COAL", "CPIN", "CPRI", "CSAP", "CSIS", "CSRA", "CTBN", "CTRA", 
	"CTTH", "DART", "DDEI", "DEAL", "DEWA", "DEXA", "DFAM", "DGIK", "DIGI", "DILD", 
	"DIVA", "DKFT", "DLTA", "DMAS", "DNAR", "DNET", "DOID", "DPNS", "DRMA", "DSFI", 
	"DSNG", "DSSA", "DUTI", "DVLA", "DWGL", "EAST", "ECII", "ENRG", "ERAA", "ERTX", 
	"ESSA", "ESTI", "ETWA", "EXCL", "FAST", "FASW", "FILM", "FPNI", "FREN", "GAMA", 
	"GDST", "GEMA", "GGRM", "GIAA", "GJTL", "GLOB", "GOLD", "GOOD", "GPRA", "GOTO", 
	"GRPM", "GSMF", "GWSA", "GZCO", "HATM", "HDFA", "HDTX", "HERO", "HEXA", "HITS", 
	"HMSP", "HOKI", "HOME", "HOPE", "HRTA", "HRUM", "IATA", "IBFN", "IBST", "ICBP", 
	"ICON", "IDPR", "IGAR", "IIKP", "IKAI", "IKBI", "IMAS", "IMJS", "INCF", "INAF", 
	"INCI", "INDF", "INDY", "INKP", "INPP", "INPS", "INRU", "INTD", "INTP", "IPCC", 
	"IPPE", "IPOL", "IRRA", "ISAT", "ISSP", "ITMG", "ITIC", "JECC", "JMAS", "JPFA", 
	"JRPT", "JSMR", "JSPT", "JTPE", "KAEF", "KARW", "KBLI", "KBLM", "KBAG", "KDSI", 
	"KIAS", "KICI", "KIJA", "KKGI", "KLBF", "KMTR", "KOBX", "KOIN", "KOCI", "KPIG", 
	"KRAS", "KREN", "LPCK", "LPGI", "LPLI", "LPPF", "LPKR", "LRNA", "LSIP", "LTLS", 
	"LUCK", "MAPB", "MAPI", "MARI", "MASB", "MAYA", "MBAP", "MBSS", "MBTO", "MCOR", 
	"MCOL", "MDKA", "MDKI", "MDLN", "MDIA", "MEDC", "MEGA", "METR", "MFIN", "MFMI", 
	"MGNA", "MIKA", "MIRA", "MITI", "MKPI", "MLBI", "MLIA", "MLPL", "MLPT", "MNCN", 
	"MPPA", "MPRO", "MPMX", "MRAT", "MREI", "MSIN", "MSKY", "MTDL", "MTFN", "MTLA", 
	"MTPS", "MYOH", "MYOR", "MYRX", "NELY", "NIKL", "NIPS", "NIRO", "NISP", "NOBU", 
	"NRCA", "NTR R", "OASA", "OKAS", "OMRE", "OPMS", "PADI", "PALM", "PANR", "PANS", 
	"PBID", "PBSA", "PCAR", "PDES", "PEGE", "PGAS", "PGJO", "PGLI", "PGUN", "PICO", 
	"PJAA", "PKPK", "PLIN", "PLAS", "PNBN", "PNBS", "PNIN", "PNLF", "PNSE", "POLY", 
	"POOL", "PORT", "POWR", "PPGL", "PPRE", "PPRO", "PRDA", "PRIM", "PRAS", "PSAB", 
	"PSDN", "PSGO", "PSKT", "PTDU", "PTIS", "PTPP", "PTRO", "PTSN", "PTPN", "PZZA", 
	"RBMS", "RANC", "RDTX", "RELI", "RICY", "RIGS", "RIMO", "RISE", "RMKE", "RODA", 
	"ROTI", "RUIS", "SAFE", "SAME", "SAMF", "SAPX", "SCCO", "SCMA", "SCNP", "SDRA", 
	"SFXI", "SGER", "SGRO", "SHID", "SILO", "SIMP", "SIPD", "SKBM", "SKLT", "SMAR", 
	"SMBR", "SMCB", "SMDM", "SMDR", "SMGR", "SMRA", "SMTU", "SMSM", "SNLK", "SOCHI", 
	"SOCI", "SONA", "SOSI", "SOTN", "SPMA", "SPTO", "SQMI", "SREI", "SRIL", "SRTG", 
	"SSIA", "SSMS", "SSSS", "SSTR", "STAA", "STAR", "STTP", "SUGI", "SULI", "SUPR", 
	"TALF", "TAPG", "TARA", "TAXI", "TBIG", "TBLA", "TBMS", "TCID", "TELE", "TFCO", 
	"TGKA", "TIFA", "TIMS", "TINS", "TIRA", "TPIA", "TPMA", "TRAM", "TRIL", "TRIM", 
	"TRIN", "TRIO", "TRIS", "TRST", "TRUK", "TSPC", "TOTO", "TOWR", "TOPS", "UCID", 
	"ULTJ", "UNIC", "UNIQ", "UNTR", "UNVR", "URBN", "VRNA", "WAPO", "WEGE", "WEHA", 
	"WICN", "WIFI", "WIIM", "WIMB", "WINS", "WIRT", "WOOD", "WOWS", "WSBP", "WSKT", 
	"WTON", "YPAS", "YULE", "ZBRA", "ZINC"
];